# Nexus Green Production Docker Compose - Optimized for AWS t4g.medium

services:
  nexus-green:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      platforms:
        - linux/arm64
    container_name: nexus-green
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_APP_NAME=NexusGreen
      - VITE_APP_VERSION=6.1.0
      - VITE_API_URL=/api
      - VITE_ENVIRONMENT=production
      - VITE_COMPANY_NAME=SolarTech Solutions (Pty) Ltd
      - VITE_COMPANY_REG=2019/123456/07
      - VITE_PPA_RATE=1.20
    networks:
      - nexus-network
    depends_on:
      nexus-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.nexusgreen.service=frontend"
      - "com.nexusgreen.version=6.1.0"
    # Memory limits for t4g.medium
    mem_limit: 512m
    memswap_limit: 512m

  # API backend service
  nexus-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: nexus-api
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://nexususer:nexuspass123@nexus-db:5432/nexusgreen
      - JWT_SECRET=nexus-green-jwt-secret-2024
      - SOLAX_SYNC_INTERVAL_MINUTES=60
      - CORS_ORIGIN=*
    networks:
      - nexus-network
    depends_on:
      nexus-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Memory limits for t4g.medium
    mem_limit: 256m
    memswap_limit: 256m

  # Database service with seeding
  nexus-db:
    image: postgres:15-alpine
    platform: linux/arm64
    container_name: nexus-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nexusgreen
      - POSTGRES_USER=nexususer
      - POSTGRES_PASSWORD=nexuspass123
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - nexus-db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexususer -d nexusgreen"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Memory limits for t4g.medium
    mem_limit: 512m
    memswap_limit: 512m
    shm_size: 128m

networks:
  nexus-network:
    driver: bridge

volumes:
  nexus-db-data:
    name: nexus-green-db-data
