version: '3.8'

services:
  nexus-db:
    image: postgres:15-alpine
    container_name: nexus-db
    environment:
      POSTGRES_DB: nexusgreen_db
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - nexus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus_user -d nexusgreen_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  nexus-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: nexus-api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://nexus_user:nexus_secure_password_2024@nexus-db:5432/nexusgreen_db
      JWT_SECRET: nexus_super_secure_jwt_secret_key_2024_production
      JWT_EXPIRES_IN: 24h
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      nexus-db:
        condition: service_healthy
    networks:
      - nexus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nexus-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-green
    ports:
      - "8080:80"
    networks:
      - nexus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  nexus-network:
    driver: bridge