apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexusgreen-backend
  labels:
    app: nexusgreen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexusgreen-backend
  template:
    metadata:
      labels:
        app: nexusgreen-backend
    spec:
      containers:
      - name: backend
        image: nexusgreen-backend:1.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          value: "postgresql://nexusgreen:nexusgreen@postgres-service:5432/nexusgreen"
        - name: DB_USER
          value: "nexusgreen"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "nexusgreen"
        - name: DB_PASSWORD
          value: "nexusgreen"
        - name: DB_PORT
          value: "5432"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nexusgreen-backend
  labels:
    app: nexusgreen-backend
spec:
  selector:
    app: nexusgreen-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP