apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexusgreen-frontend
  labels:
    app: nexusgreen-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexusgreen-frontend
  template:
    metadata:
      labels:
        app: nexusgreen-frontend
    spec:
      containers:
      - name: frontend
        image: nexusgreen-frontend:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://nexusgreen-backend:3001/api"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nexusgreen-frontend
  labels:
    app: nexusgreen-frontend
spec:
  selector:
    app: nexusgreen-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nexusgreen-nodeport
  labels:
    app: nexusgreen-frontend
spec:
  selector:
    app: nexusgreen-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: NodePort