apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nexus-green
data:
  NODE_ENV: "production"
  PORT: "3001"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "nexus_green"
  DB_USER: "nexus_user"
  DB_PASSWORD: "nexus_password_2024"
  JWT_SECRET: "nexus_green_jwt_secret_2024_production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-api
  namespace: nexus-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-api
  template:
    metadata:
      labels:
        app: nexus-api
    spec:
      containers:
      - name: nexus-api
        image: nexus-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-api
  namespace: nexus-green
spec:
  selector:
    app: nexus-api
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP