apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-api-config
  namespace: nexus-green-prod
data:
  NODE_ENV: "production"
  PORT: "3001"
  DATABASE_URL: "postgresql://nexusgreen:nexusgreen_secure_password_2024@postgres:5432/nexusgreen"
  JWT_SECRET: "your-super-secure-jwt-secret-key-for-production-2024"
  JWT_EXPIRES_IN: "24h"
  CORS_ORIGIN: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-api
  namespace: nexus-green-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexus-api
  template:
    metadata:
      labels:
        app: nexus-api
    spec:
      containers:
      - name: nexus-api
        image: nexus-green-api:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: nexus-api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-api
  namespace: nexus-green-prod
spec:
  selector:
    app: nexus-api
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP